Ajusta requisições enviadas para a Vindi
vindi/vindi-woocommerce-subscriptions pull request #101
Opened 2018-09-20 23:06 UTC by laerte-guimaraes

## Motivação
Atualmente o plugin da Vindi realiza em média 12 requisições para realizar uma compra, pois algumas informações são consultadas várias vezes e não persistidas.

## Solução Proposta
Realizar uma refatoração nas consultas e tratamento dos retornos, para diminuir o número de requisições.

2018-09-24 14:55 UTC, rtakauti requested changes

2018-09-24 14:55 UTC, rtakauti commented on includes/class-vindi-api.php
> +        if (false == $vindi_customer['id']) {
Pode dar fatal error caso "find_customer_by_code" retorne falso

2018-09-24 15:35 UTC, rtakauti commented on includes/class-vindi-api.php
> +            return $this->create_customer($wc_customer);
Pode dar erro caso "find_customer_by_code" retorne falso

2018-09-24 18:29 UTC, rtakauti approved these changes

2018-09-26 16:29 UTC, asagalo approved these changes
Nice :star2:

2018-10-02 20:50 UTC, merged