Cria infraestrutura de testes
vindi/vindi-woocommerce-subscriptions pull request #108
Opened 2018-10-19 20:43 UTC by rtakauti

# Motivação
Por não haver testes e poder assegurar a qualidade do código, foi visto a necessidade de cria-los

# Solução proposta
Criação de testes unitários, funcionais e aceitação

2018-10-23 13:54 UTC, laerte-guimaraes requested changes
Acredito que a infraestrutura de testes deva ser finalizada no ajuste do composer.json.

Os demais commits serão incorporados após a merge desse PR.

Está sendo exibido um erro nos testes tbm :-1: 
![image](https://user-images.githubusercontent.com/31661772/47365449-f69f7180-d6b1-11e8-9435-5249b42f1288.png)

2018-10-23 18:35 UTC, laerte-guimaraes approved these changes

2018-10-24 22:53 UTC, lyoncesar reviewed
@rtakauti como comentei antes, sugiro a adição do @talesgalvao e o @asagalo nesse PR, acho que eles podem contribuir positivamente na revisão :smiley:

2018-10-24 22:54 UTC, lyoncesar approved these changes

2018-10-25 23:22 UTC, lyoncesar requested changes
@rtakauti como falamos, estou sentindo falta de mais informações na descrição do PR, por exemplo:
Porque foi escolhido esse framework?
Quais são as vantagens e desvantagens que você vê em usarmos ele?
Como rodo os testes no meu ambiente de dev?
Também tomei a liberdade de adicionar o @talesgalvao e o @asagalo como revisores por entender que essa é uma decisão importante a ser tomada e o @laerte-guimaraes e eu não conseguimos opinar de forma muito construtiva no nível de conhecimento que a funcionalidade precisa.

2018-10-26 02:06 UTC, rtakauti commented
Como eu disse não vou ter muitas respostas de benchmark por se tratar mais um conceito de uma POC, e ja foi relatado porque da escolha por se tratar de testes isolados, alem de que é possivel realizar testes unitarios, funcionais e aceitação

2018-10-26 15:14 UTC, lyoncesar approved these changes
Ainda acho que a descrição pode ser melhorada, mas não vou segurar o PR por isso :smiley:

2018-10-31 14:14 UTC, merged