Simplifica a documentação
vindi/vindi-woocommerce-subscriptions pull request #131
Opened 2019-08-02 19:00 UTC by wagner

## Motivação
As instruções de instalação e requisitos estão inconsistentes em vários lugares diferentes (blog, Zendesk, README, etc), gerando desinformação e dúvida.

## Solução Proposta
Em vez de repetir as instruções de instalação e requisitos, queremos manter isso atualizado em apenas um único lugar. Por enquanto o lugar escolhido foi o [artigo no Zendesk Vindi](https://atendimento.vindi.com.br/hc/pt-br/articles/227335608-Como-instalo-o-Vindi-WooCommerce-Subscriptions-).

2019-08-02 19:06 UTC, st3llaris approved these changes

2019-08-02 19:42 UTC, leo-araujo approved these changes

2019-08-02 19:46 UTC, luismollaveloso approved these changes

2019-08-02 19:54 UTC, laerte-guimaraes commented on README.md
> +# Vindi WooCommerce Subscriptions
```suggestion
# Vindi WooCommerce
```

2019-08-02 19:56 UTC, laerte-guimaraes requested changes
O plugin mudou a nomenclatura no PR #76

E passou a ser somente **Vindi WooCommerce**

2019-08-02 20:08 UTC, laerte-guimaraes commented on README.md
> +O **Vindi WooCommerce Subscriptions** oferece uma solução completa para pagamentos únicos e assinaturas com cartão de crédito e boleto utilizando o [Woocommerce Subscriptions](https://www.woothemes.c
```suggestion
O **Vindi WooCommerce** oferece uma solução completa para pagamentos únicos e assinaturas com cartão de crédito e boleto utilizando o [Woocommerce Subscriptions](https://www.woothemes.com/products/woocommerce-subscriptions/). Basta ter [uma conta habilitada na Vindi](https://www.vindi.com.br/cadastro/) para começar a cobrar seus clientes.
```

2019-08-02 20:08 UTC, laerte-guimaraes commented on README.md
> +# Vindi WooCommerce Subscriptions
```suggestion
# Vindi WooCommerce
```

2019-08-02 20:08 UTC, laerte-guimaraes commented on readme.txt
> +O **Vindi WooCommerce Subscriptions** oferece uma solução completa para pagamentos únicos e assinaturas com cartão de crédito e boleto utilizando o [Woocommerce Subscriptions](https://www.woothemes.c
```suggestion
O **Vindi WooCommerce** oferece uma solução completa para pagamentos únicos e assinaturas com cartão de crédito e boleto utilizando o [Woocommerce Subscriptions](https://www.woothemes.com/products/woocommerce-subscriptions/). Basta ter [uma conta habilitada na Vindi](https://www.vindi.com.br/cadastro/) para começar a cobrar seus clientes.
```

2019-08-02 20:08 UTC, laerte-guimaraes commented on readme.txt
> -= Requisitos =
Faz sentido remover toda a documentação da página de descrição do plugin?
É importante ressaltar, que isso obriga o usuário a acessar o site da Vindi para verificar os requisitos, etc.
Ex:
![image](https://user-images.githubusercontent.com/31661772/62395921-12407e00-b548-11e9-9e18-e86ff133646c.png)

2019-08-06 13:11 UTC, wagner commented on readme.txt
> -= Requisitos =
Sim, é exatamente esse o objetivo. Caso contrário teremos instruções e requisitos duplicados em vários lugares diferentes, o que vai promover inconsistências entre eles.

2019-08-06 13:49 UTC, vitorkusiaki commented on readme.txt
> +Para dúvidas e suporte técnico, entre em contato com a equipe Vindi através da nossa [central de atendimento](http://atendimento.vindi.com.br/hc/pt-br).
```suggestion
Para dúvidas e suporte técnico, entre em contato com a equipe Vindi através da nossa [central de atendimento](https://atendimento.vindi.com.br/hc/pt-br).
```

2019-08-06 13:50 UTC, vitorkusiaki commented on readme.txt
> +A [Vindi](http://www.vindi.com.br/) é líder em cobrança recorrente no Brasil. Com milhares de clientes usando soluções como pagamento online, soluções de notas fiscais integradas, emissão de boletos
```suggestion
A [Vindi](https://www.vindi.com.br/) é líder em cobrança recorrente no Brasil. Com milhares de clientes usando soluções como pagamento online, soluções de notas fiscais integradas, emissão de boletos por email e PDF, integrações com ERPs e diversos relatórios, a Vindi possibilita um sistema online completo para negócios de venda recorrente. Além disso, empresas podem usar o gateway de pagamento integrado ao billing recorrente ou para faturas avulsas.
```

2019-08-06 13:51 UTC, vitorkusiaki commented on README.md
> +Para dúvidas e suporte técnico, entre em contato com a equipe Vindi através da nossa [central de atendimento](http://atendimento.vindi.com.br/hc/pt-br).
```suggestion
Para dúvidas e suporte técnico, entre em contato com a equipe Vindi através da nossa [central de atendimento](https://atendimento.vindi.com.br/hc/pt-br).
```

2019-08-06 13:51 UTC, vitorkusiaki commented on README.md
> +A [Vindi](http://www.vindi.com.br/) é líder em cobrança recorrente no Brasil. Com milhares de clientes usando soluções como pagamento online, soluções de notas fiscais integradas, emissão de boletos
```suggestion
A [Vindi](https://www.vindi.com.br/) é líder em cobrança recorrente no Brasil. Com milhares de clientes usando soluções como pagamento online, soluções de notas fiscais integradas, emissão de boletos por email e PDF, integrações com ERPs e diversos relatórios, a Vindi possibilita um sistema online completo para negócios de venda recorrente. Além disso, empresas podem usar o gateway de pagamento integrado ao billing recorrente ou para faturas avulsas.
```

2019-08-06 19:36 UTC, laerte-guimaraes approved these changes
![img](https://media1.giphy.com/media/69zJh9MFntTPSd0U0W/giphy.gif?cid=790b76115d49d6a54755425551a2120b&rid=giphy.gif)

2019-08-08 15:10 UTC, merged

2019-08-08 15:10 UTC, wagner commented
@vitorkusiaki apliquei seus comentários! Valeu!!