Adiciona validação para assinatura Variável no carrinho
vindi/vindi-woocommerce-subscriptions pull request #146
Opened 2020-03-14 00:55 UTC by LeoAraujo01

## Motivação
Ao adicionar 2 assinaturas variáveis de planos diferentes no carrinho não havia bloqueio para está ação pelo plugin, deste modo os clientes podiam adicionar uma assinatura anual e uma mensal que levaria o cliente ao erro visto que será utilizado somente 1 plano para os produtos adicionados no carrinho.   

## Solução Proposta
Adicionar junto a validação no carrinho para produtos do tipo **assinatura** o tipo de produto **assinatura variável**.

2020-03-14 01:27 UTC, laerte-guimaraes commented on vindi-woocommerce-subscriptions.php
> +                    if ('subscription' || 'variable-subscription' === $item['data']->product_type) {
```suggestion
                    if ('subscription' === $item['data']->product_type || 'variable-subscription' === $item['data']->product_type) {
```

2020-03-14 01:27 UTC, laerte-guimaraes commented on vindi-woocommerce-subscriptions.php
> +                    if ('subscription' || 'variable-subscription' === $item['data']->product_type) {
Ou você pode usar algo como `in_array`.

Pra tentar deixar um pouco mais legível você pode abstrair essas validações para um novo método. Ex:
````php
is_product_type_subscription($product, 'product');
is_product_type_subscription($item, 'cart_item');

function is_product_type_subscription($object, $type)
{
  if ($type === 'product') {
    return $object->is_type('subscription') || $object->is_type('variable-subscription');
  }

  return  in_array($object['data']->product_type, array('subscription' , 'variable-subscription');
}
````

2020-03-14 01:30 UTC, laerte-guimaraes commented on vindi-woocommerce-subscriptions.php
> +                    if ('subscription' || 'variable-subscription' === $item['data']->product_type) {
Ou abastrair uma a uma:
````php
is_new_product_subscription($product);

function is_new_product_subscription($product)
{
    return $object->is_type('subscription') || $object->is_type('variable-subscription');
}

is_cart_item_subscription($item);

function is_cart_item_subscription($cart_item)
{
  return  in_array($cart_item['data']->product_type, array('subscription' , 'variable-subscription');
}
````

2020-03-25 16:39 UTC, dannnylo requested changes

2020-03-25 16:39 UTC, dannnylo commented on vindi-woocommerce-subscriptions.php
> +
Esta linha em branco não é necessária.

```suggestion
            if ($this->is_new_product_subscription($product)) {
```

2020-03-25 16:39 UTC, dannnylo commented on vindi-woocommerce-subscriptions.php
> +            $subscriptions_types = array('subscription' , 'variable-subscription');
```suggestion
            $subscriptions_types = array('subscription', 'variable-subscription');
```

2020-03-25 19:44 UTC, st3llaris approved these changes

2020-03-25 19:47 UTC, laerte-guimaraes approved these changes

2020-03-25 19:48 UTC, LeoAraujo01 commented on vindi-woocommerce-subscriptions.php
> +
Alterações realizadas no commit https://github.com/vindi/vindi-woocommerce-subscriptions/pull/146/commits/5fb9a15365658d663be42116031e61e8c7d038f3

2020-03-26 10:59 UTC, dannnylo approved these changes

2020-03-26 13:42 UTC, laerte-guimaraes requested changes
@LeoAraujo01 pode fazer o versionamento? :wink:

2020-03-26 15:48 UTC, closed without merging

2020-03-26 15:51 UTC, LeoAraujo01 commented
Fechando PR temporariamente! 

Ao realizar novos testes, verifiquei que o data do item retorna vazio, neste caso o mesmo não está sendo preenchido para assinatura do tipo variável.

Estou analisando uma forma para preencher está informação para assinaturas variáveis para reabrir o PR.