atualizacao de compatibilidade para o wc3
vindi/vindi-woocommerce-subscriptions pull request #31
Opened 2017-05-10 14:40 UTC by lyoncesar

Foram feitos alguns ajustes para que o plugin funcione com o WooCommerce acima da versão 3.0.

2017-05-11 12:26 UTC, wagner commented
@lyoncesar essa atualização quebra a compatibilidade com a versão 2.

2017-05-11 12:27 UTC, wagner submitted a review, later dismissed
Essa atualização quebra compatibilidade com a versão 2.

2017-05-19 15:33 UTC, asagalo requested changes
Seria legal acertar as informações sobre a mudança e tags de compatibilidade no readme.txt e vindi-woocommerce-subscriptions.php

2017-05-27 17:49 UTC, asagalo approved these changes

2017-05-27 21:28 UTC, merged