Ajuste na renovacao de pedidos [INT-3]
vindi/vindi-woocommerce-subscriptions pull request #35
Opened 2017-07-14 22:25 UTC by lyoncesar

Adicionada a funcionalidade para criação de pedidos á partir do webhook bill_paid.

2017-07-18 20:15 UTC, DNA requested changes

2017-07-18 20:15 UTC, DNA commented on includes/class-vindi-webhook-handler.php
> +        if(!empty($data->bill->subscription)) {
Ao invés de colocar a função *inteira* dentro de um `if`, é melhor usar uma [Guard Clause](http://wiki.c2.com/?GuardClause):
```PHP
if (empty($data->bill->subscription)) return;
```

2017-07-18 20:15 UTC, DNA commented on includes/class-vindi-webhook-handler.php
>              $wc_subscription_id    = $data->bill->subscription->code;
Essa variável não está sendo usada em lugar algum no método, pode removê-la

2017-07-18 20:15 UTC, DNA commented on includes/class-vindi-webhook-handler.php
>              $order                 = $this->find_order_by_subscription_and_cycle($vindi_subscription_id, $cycle);
Pode remover esse `$order = ` e chamar o método direto, já que essa informação não está sendo usada em lugar algum

2017-07-18 20:15 UTC, DNA commented on includes/class-vindi-webhook-handler.php
>              $order                 = $this->find_order_by_subscription_and_cycle($vindi_subscription_id, $cycle);
Ou melhor, você está procurando essa `$order` com qual objetivo?

2017-07-18 23:09 UTC, wagner requested changes
Onde estão os testes?

2017-07-19 18:18 UTC, rodrigo approved these changes
Testei junto ao Lyon e funcionou corretamente.

2017-07-20 22:03 UTC, wagner commented
@rodrigorbltt me referia à testes automatizados.

@lyoncesar organize alguma estrutura de testes automatizados para o próximo release. Acredito que o @DNA pode ajudar a indicar ferramentas.

2017-07-20 22:03 UTC, wagner approved these changes

2017-07-21 21:07 UTC, DNA approved these changes

2017-07-21 22:20 UTC, merged