Fix/ambiente sandbox
vindi/vindi-woocommerce-subscriptions pull request #43
Opened 2017-09-12 16:36 UTC by lyoncesar

Ajustes feitos no plugin para trabalhar com ambiente sandbox da Vindi ao invés da conta trial.

2017-09-12 16:46 UTC, laerte-guimaraes requested changes

2017-09-12 16:46 UTC, laerte-guimaraes commented on includes/class-vindi-api.php
>          return 'https://staging-app.vindi.com.br/api/v1/';
return 'https://app.vindi.com.br/api/v1/;

2017-09-12 19:27 UTC, DNA requested changes
A implementação de `is_sandbox_merchant` está confusa e tem de ser revista, para evitar problemas futuros

2017-09-12 19:27 UTC, DNA commented on includes/class-vindi-api.php
> +    public function is_sandbox_merchant()
Corrija tb o doc desse método, já que agora ele não faz a mesma coisa de antes.

2017-09-12 19:27 UTC, DNA commented on includes/class-vindi-api.php
> +     * @var Yes/no
Coloque o valor das stringa na description:
`@var string "Yes or No"`

2017-09-12 19:27 UTC, DNA commented on includes/class-vindi-api.php
> +     * @param Vindi_Settings $container
A documentação está errada. E `$sandbox` não deveria ser uma string?

2017-09-12 19:27 UTC, DNA commented on includes/class-vindi-settings.php
> +     * @param $text highlight_string(str)
A ordem está errada, é `@param type $name`. E o que é esse `highlight_string`?

2017-09-12 19:27 UTC, DNA commented on includes/class-vindi-api.php
> +    public function is_sandbox_merchant()
Olhando o resto do código, esse método não retornar mais um valor booleano pode abrir um numero bem grande de bugs, já que os testes não verificam o conteúdo dele

2017-09-13 14:15 UTC, lyoncesar commented
Pessoal, fiz os ajustes indicados. Vocês conseguem dar uma olhada?

Abs.

2017-09-13 17:37 UTC, DNA requested changes

2017-09-13 17:37 UTC, DNA commented on includes/class-vindi-api.php
> +            return 'true';
`true` está sendo passado como string

2017-09-13 17:37 UTC, DNA commented on includes/class-vindi-api.php
> +        return [];
Pq um `array` vazio ao invés de `false`?

2017-09-13 17:37 UTC, DNA commented on includes/class-vindi-bank-slip-gateway.php
> +        $is_trial = $this->container->api->is_sandbox_merchant();
Troca essa variável pra `$is_sandbox`, pra evitar confusão

2017-09-13 17:37 UTC, DNA commented on includes/class-vindi-creditcard-gateway.php
> +        $is_trial = $this->container->api->is_sandbox_merchant();
Troca essa variável pra `$is_sandbox`, pra evitar confusão

2017-09-13 17:53 UTC, DNA approved these changes

2017-09-13 17:57 UTC, lyoncesar commented
Pessoal, fiz um ajuste no método que o @DNA indicou.
Ele estava verificando apenas se um merchant está no Sandbox, agora ele verifica que se a conta está em trial ou no Sandbox.
Esse método é usado ns verificação de utilização do ssl e desativa os métodos de pagamento da Vindi caso não tenha o SSL.
Acredito que dessa forma ficou melhor :)

2017-09-14 14:24 UTC, laerte-guimaraes approved these changes

2017-09-14 14:29 UTC, laerte-guimaraes approved these changes

2017-09-14 15:16 UTC, merged