[INT-60] Feature/Cancelamento WC-Memberships
vindi/vindi-woocommerce-subscriptions pull request #49
Opened 2017-10-18 21:30 UTC by lyoncesar

## Motivação
O WC-Subscriptions possui integração com um plugin chamado WC-Memberships, esse plugin faz um controle de acesso ao portal do nosso cliente baseado no status das assinaturas do WC-Subscriptions.
Os clientes que usam esse tipo de integração não estão conseguindo fazer o cancelamento de uma assinatura sem impactar o acesso do cliente final, isso porque ao solicitar o cancelamento de uma assinatura na área do cliente o nosso plugin faz o cancelamento imediato da assinatura.
Conforme a documentação do WC-Subscriptions, o comportamento ideal seria manter a assinatura com o status 'pending cancelation':
https://docs.woocommerce.com/document/subscriptions/statuses/
![screenshot from 2017-10-18 19-21-29](https://user-images.githubusercontent.com/15332442/31743354-a33bafc2-b439-11e7-85d7-0f8c546f86dc.png)
## Solução
Apenas usando  o status 'pending cancelation' o problema não foi resolvido porque o WC faz o cancelamento da assinatura baseado no horário de criação dela.
_Ex: Uma assinatura mensal gerada ás 16hs do dia 01/10 será cancelada apenas ás 16hs do dia 01/11._
Para evitar a cobrança de uma assinatura já cancelada acredito que a melhor opção seja cancelar a assinatura na Vindi assim que o cliente solicitar. No WCS a assinatura fica pendente de cancelamento garantindo com isso o acesso do cliente até o termino do período pago e evitando a cobrança da assinatura cancelada.

2017-10-19 13:54 UTC, michelsazevedo approved these changes

2017-10-19 17:53 UTC, DNA requested changes
Só um detalhe simples dessa vez, seu php-fu tá ficando cada vez melhor :+1:

2017-10-19 17:53 UTC, DNA commented on includes/class-vindi-subscription-status-handler.php
> +    public function get_vindi_subscription_id($wc_subscription_id)
Ao invés de receber `$wc_subscription_id` (que está diferente do que o doc acima diz), vc pode só receber o `$wc_subscription` completo e chamar o `$wc_subscription->id` no post meta, assim vc não precisa fazer isso nas chamadas pra essa função

2017-10-20 16:59 UTC, lyoncesar commented on includes/class-vindi-subscription-status-handler.php
> +    public function get_vindi_subscription_id($wc_subscription_id)
Atualizei, commit enviado :)

2017-10-20 19:36 UTC, DNA approved these changes

2017-10-26 15:35 UTC, brunoadacosta approved these changes
:+1:

2017-10-27 17:01 UTC, merged

2017-10-30 14:10 UTC, renanno commented
Dúvida: com essa mudança precisamos cancelar a assinatura a partir do WCS e não da plataforma Vindi?

Se eu cancelar uma assinatura pela plataforma Vindi, hoje o WCS e WCM cancelam imediatamente o acesso. Isso não muda? Não ficou claro.