Remoção das informações adicionais dos produtos
vindi/vindi-woocommerce-subscriptions pull request #51
Opened 2017-10-24 15:47 UTC by laerte-guimaraes

Foram removidas as informações adicionais referentes ao cadastro da Vindi exibidas ao finalizar a compra de um produto.

2017-10-24 16:56 UTC, DNA requested changes
Faltou também mencionar o motivo da alteração na descrição do PR

2017-10-24 16:56 UTC, DNA commented on includes/class-vindi-payment.php
>          $order_items[]  = $this->build_shipping_item();
Como vc removeu a definição do `$order_items`, isso vai gerar um warning quando vc tentar atribuir um index a um array que não existe. Sugiro usar uma dessas duas formas, a que vc achar melhor:

```php
$order_items  = [$this->build_shipping_item()];
```
ou
```php
$order_items = [];
$order_items[]  = $this->build_shipping_item();
```

2017-10-25 12:53 UTC, DNA approved these changes

2017-10-27 16:21 UTC, wagner commented
@laerte-guimaraes pode colocar um print do antes e depois?

2017-10-27 17:15 UTC, laerte-guimaraes commented
@wagner 
Claro :)

Os aspectos variam de acordo com o tema utilizado, mas as informações são sempre as mesmas.

![image](https://user-images.githubusercontent.com/31661772/32116476-904ce5d8-bb29-11e7-9de9-612d4b9b9865.png)

2017-11-14 14:40 UTC, lyoncesar approved these changes

2017-11-14 14:40 UTC, merged