Issue #18 - Adequação de métodos p/ WooCommerce 3.0
vindi/vindi-woocommerce-subscriptions pull request #58
Opened 2017-12-05 20:38 UTC by laerte-guimaraes

A função 'woocommerce_clean' foi desativada na versão 3.0 do Woocommerce. A substituição oferecida pelo próprio plugin é a função 'wc_clean'.

2017-12-15 16:10 UTC, lyoncesar requested changes
Tentei fazer uma compra de assinatura e retornou 'invalid_parameter: code':
![screenshot from 2017-12-15 14-04-05](https://user-images.githubusercontent.com/15332442/34050345-a642447a-e1a1-11e7-9508-f653f92b798b.png)

2017-12-15 21:29 UTC, lyoncesar commented
Os errors não aconteceram mais. Vou deixar em testes na máquina que temos na aws para garantir que não vamos ter problemas.

2018-01-22 15:36 UTC, lyoncesar reviewed
Vou fazer esses testes de novo hoje e se estiver tudo funcionando já aprovo o PR.

2018-03-01 18:46 UTC, lyoncesar commented
@laerte-guimaraes, estou encerrando esse PR.
Me avise quando puder testar esse comportamento e nós podemos reabrir o PR.

2018-06-21 13:06 UTC, laerte-guimaraes commented
@rtakauti Realizei novos testes e não consegui reproduzir a situação informada pelo @lyoncesar;

Podemos avançar nessa correção?

2018-06-28 15:01 UTC, rtakauti approved these changes

2018-06-28 15:02 UTC, laerte-guimaraes reviewed
@lyoncesar ,

O erro apresentado é da fatura que está indo com o código igual ao já cadastrado na plataforma.

Verifiquei que o método não realiza alterações nesse processo.

2018-06-28 15:22 UTC, carolina-y approved these changes

2018-06-28 18:05 UTC, merged