[INT-79] Feature/Remove dependência do WCS
vindi/vindi-woocommerce-subscriptions pull request #65
Opened 2017-12-13 16:35 UTC by lyoncesar

# Motivação
Temos recebido pedidos dos nossos clientes para removermos a dependência do WooCommerce Subscriptions (WCS). Isso porque muitos só fazem vendas avulsas.

# Solução
Fiz a remoção de dependência do WCS e testei o comportamento do plugin apenas usando o WooCommerce e Extra checkout fieldz for Brazil. O plugin funcionou normalmente.
Aproveitei para refatorar os métodos responsáveis por fazer a validação de dependências do plugin, isso vai ajudar em casos futuros.

2017-12-13 16:48 UTC, laerte-guimaraes requested changes
Acredito que esteja difícil a compreensão de onde foram atribuídas ($version_match[0] e $version_match[1]).

Poderia ser mais claro?

2017-12-13 20:27 UTC, lyoncesar commented
Adicionei um índice, acredito que isso ajude.

2017-12-15 17:11 UTC, laerte-guimaraes requested changes

2017-12-15 17:11 UTC, laerte-guimaraes commented on includes/class-vindi-dependencies.php
> +    public function wc_memberships_are_activated()
O método está sendo chamado na linha 206 de (class-vindi-webhook-handler.php)

2017-12-15 19:17 UTC, laerte-guimaraes approved these changes
🐤

2017-12-19 14:30 UTC, brunoadacosta approved these changes
:+1:

2017-12-21 13:58 UTC, merged