Adiciona ciclos do cupom na assinatura
vindi/vindi-woocommerce-subscriptions pull request #94
Opened 2018-08-20 22:20 UTC by laerte-guimaraes

## Motivação
A configuração de duração de cupons em uma assinatura é **global**; Sendo assim, se definir duração de 1 ciclo, a duração será refletida para todos os cupons.
Alguns clientes desejam utilizar uma duração personalizada por cupons.

## Solução Proposta
A alteração, disponibiliza a opção de utilizar a duração configurada no cupom como duração do desconto na assinatura.

2018-08-24 14:35 UTC, carolina-y commented on includes/class-vindi-payment.php
> +        $get_plan_lenght =
Pode trocar por `$get_plan_length`?

2018-08-24 14:38 UTC, carolina-y approved these changes

2018-08-24 15:20 UTC, laerte-guimaraes commented on includes/class-vindi-payment.php
> +        $get_plan_lenght =
:laughing: sorry :female_detective:

2018-08-24 16:53 UTC, laerte-guimaraes commented
@lyoncesar conforme conversado, alterei a localização para **Limite de uso por cliente**; Pois, o _Limite de uso por cupom_ é global, e qualquer cliente que utilize o mesmo, consome esse limite.

![image](https://user-images.githubusercontent.com/31661772/44597128-0c251780-a7a5-11e8-838e-33f066d11f4a.png)

2018-08-24 17:13 UTC, laerte-guimaraes commented
**Ex:**
> Você pode criar um desconto com **limite de uso** em 2 por cliente, e disponibilizá-lo na _Black Friday_.
Cada cliente que utilizar irá receber o desconto de **2 ciclos**, e você pode utilizar a _data de expiração do cupom_ no WooCommerce, para definir _até quando_ o cupom poderá ser utilizado.

A data de expiração é um campo do tipo _data_, e pode causar um *impacto indesejado* em empresas que utilizam recorrências semanais/diárias/bimestrais/semestrais/anuais

Essa é a única forma de disponibilizar a flexibilidade de utilizar **descontos personalizados**, sem prejudicar empresas que utilizam recorrências _diferentes de mensa_.

2018-08-28 14:44 UTC, talesgalvao approved these changes

2018-08-28 15:56 UTC, lyoncesar requested changes

2018-08-28 15:56 UTC, lyoncesar commented on includes/class-vindi-payment.php
> +                return $get_plan_lenght ($customCoupon);
Peguei um erro nesse cara. O nome do método está escrito errado. O certo é get_plan_length

2018-08-28 15:57 UTC, laerte-guimaraes commented on includes/class-vindi-payment.php
> +                return $get_plan_lenght ($customCoupon);
Valeu @lyoncesar acabei de ajustar

2018-08-28 16:08 UTC, lyoncesar approved these changes
Show! :+1:

2018-08-28 16:13 UTC, merged